### PR TITLE
chore: Commit message generator

### PR DESCRIPTION
**Pull request by 84634E1A607A**
写了一个简单的生成器

### CODE REVIEW

**Review by UNIDY2002 — CHANGES_REQUESTED** [review]
It may be a good practice to check `commit-log.txt` into version control after running the script, by adding a `git add commit-log.txt` after `node .increment.js` in the preversion script.

**Comment by 84634E1A607A** [comment]
Well, I think we will manually edit Release file later anyway, so I just left it there.

**Comment by UNIDY2002** [comment]
Unfortunately, in the current workflow, the latest changes of the release file will be committed as soon as command `yarn version` gets executed, and there is no chance of editing the release file after `commit-log.txt`, so the workflow has to be refined anyway.

**Comment by 84634E1A607A** [comment]
Emm, can we make sure that the Release file contains valid content, so that we can just append the auto-generated msgs to its end?

**Comment by UNIDY2002** [comment]
I think the key is that release notes is different from commit logs, and while for some projects, commit logs can serve as release notes, in our app, however, users are not interested in commit logs (as they are in English). I think our release workflow needs a careful re-design in order for better automation.

**Comment by 84634E1A607A** [comment]
I'll close this PR for now

**Comment by UNIDY2002** [comment]
A possible alternative could be requiring developers to add an additional Chinese message in commit messages (or PRs) to describe the changes, and extract these additional messages to build up the release notes.

**Comment by UNIDY2002** [comment]
I installed [lerna](https://lerna.js.org/) and it supports changelog generation on the flow.

I tried `yarn lerna version --no-push --conventional-commits` and it created a new release with some `CHANGELOG.md`s, but it may not fit our use case without further configuration.

You may also try it, but this PR is of low priority.

**Pull request closed without merging**
